# Generated by Django 4.0.3 on 2022-04-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familiares',
            fields=[
                ('dni', models.IntegerField(primary_key=True, serialize=False)),
                ('edad', models.IntegerField()),
                ('nombre', models.CharField(max_length=35)),
            ],
        ),
    ]
